name: Build

on:
  push:
    branches:
      - "test-debian"

env:
  BUILD_TYPE: Release

jobs:
  build:
    #if: startsWith(github.ref, 'refs/tags/')

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    container: ${{ matrix.config.container }}
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        config:
          - name: bionic
            os: ubuntu-18.04
            container: ubuntu:18.04
            triplet: x64-linux
          - name: focal
            os: ubuntu-20.04
            container: ubuntu:20.04
            triplet: x64-linux
          - name: hirsute
            os: ubuntu-21.04
            container: ubuntu:21.04
            triplet: x64-linux
          - name: impish
            os: ubuntu-21.10
            container: ubuntu:21.10
            triplet: x64-linux

    env:
      APP_NAME: ppass
      APP_VERSION: "0.1.13"
      PPA_REPO: sguerri/ppa
      PPA_USER: Sébastien GUERRI
      PPA_EMAIL: 13090870+sguerri@users.noreply.github.com

    steps:
      - name: Checkout current version
        uses: actions/checkout@v2

#      - name: Setup Python
#        uses: actions/setup-python@v3.0.0
#        with:
#          python-version: '3.9'

      - name: Install dependencies
        run: |
          add-apt-repository ppa:jyrki-pulliainen/dh-virtualenv &&
          apt update &&
          apt install -y debhelper dh-virtualenv

      - name: Install python dependencies
        run: |
          pip install virtualenv build

      - name: Build deb
        run: |
          dpkg-buildpackage -us -uc

      - name: Build python
        run: |
          python3 -m build

      - name: Copy build items
        run: |
          mv ../${{env.APP_NAME}}_${{env.APP_VERSION}}_amd64.deb ./dist/

      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: dist/
          GHR_DELETE: true
          GHR_REPLACE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Pushes to PPA
#        run: |
#          git config --global user.email "${{ env.PPA_EMAIL }}" && \
#          git config --global user.name "${{ env.PPA_USER }}" && \
#          git clone --single-branch --branch master "https://x-access-token:${{ secrets.PUBLISH_PPA }}@github.com/${{ env.PPA_REPO }}.git" published && \
#          cp "${{ env.APP_NAME }}_${{ env.APP_VERSION }}_amd64_${{ matrix.config.name }}.deb" "published/dists/${{ matrix.config.name }}/${{ env.APP_NAME }}_${{ env.APP_VERSION }}_amd64.deb" && \
#          cd published && \
#          git add . && \
#          git commit -m "[${{ matrix.config.name }}] Add ${{ env.APP_NAME }}_${{ env.APP_VERSION }}_amd64.deb" && \
#          git pull --no-edit && \
#          git push -u origin master
